apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-k8s-depl
spec:
  selector:
    matchLabels:
      app: next-app
  replicas: 1
  template:
    metadata:
      labels:
        app: next-app
    spec:
      containers:
        - name: next-app
          image: wasathlk/next-k8s
---
apiVersion: v1
kind: Service
metadata:
  name: next-k8s-srv
spec:
  type: NodePort
  selector:
    app: next-app
  ports:
    - name: next-app
      port: 3000
      targetPort: 3000